#!/bin/bash

TAG=run01
NTASKS=10
OUTDIR=/path/to/output/dir/$TAG
MAPDATA=/path/to/mapdata

mpirun -n ${NTASKS} python map_cuts.py ${MAPDATA}/area/wide_01h_n.fits "s17,cmb" $OUTDIR --filedb ${MAPDATA}/s17_subsetv5/filedb.txt --dataset s17_subsetv5 --nocommon-fraction 0.3

mpirun -n ${NTASKS} python plot_cuts.py ${OUTDIR} --range 0.01
